### ISSUE TITLE
not using entrypoints for scripts

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [b33j0r/climactic#1]

**Comment by b33j0r** [comment]
Could you please add detail to this one? Are you referring to entrypoints encoded in the YAML test cases, or adding `if __name__ == "__main__"` to more modules?

**Comment by RonnyPfannschmidt** [comment]
no, the scrpt used for the testrunner is a python script with actal code,
thats a pain to turn into propperly installable wheels for example

instead of creating a script with path hacks yourself, you should declare a entrypoint and use `setup.py develop`

**Comment by b33j0r** [comment]
Ah, okay. Not hard to do and provides a tangible advantage.

**Comment by b33j0r** [comment]
See https://github.com/b33j0r/climactic/pull/5

Simple to do because importable climactic.cli.main already existed
