### ISSUE TITLE
impossible to adapt sanely to integration with pytest

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [b33j0r/climactic#2]
due to direct usage of unit-test there is no nice way to integrate this tool in pytest

**Comment by b33j0r** [comment]
Ronny, you have provided some excellent feedback. This particular issue is definitely one I want to solve before I consider the package usable in production. It currently is difficult to use with standard/existing unit tests.

I am aware of a few "hacks" which could make this work, but I'm still looking for an elegant approach. Let me know if you already have something in mind. Ideally, we'd like to make this compatible with all unittest-based test runners (nosetests, py.test, PyCharm, etc)

**Comment by RonnyPfannschmidt** [comment]
py.test is specifically not unittest based ^^ pytest only supports unit-test tests as backward compatibility

but what i'd like to do is be able to run climactic from pytest, and potentially use extra pytest features
(like fixtures)

**Comment by b33j0r** [comment]
Short of creating a plugin for pytest, do you have an idea of how this would work? The reason I mentioned unittest is that every testing framework will recognize code that is prefixed with test_ and/or uses the unittest base classes. Whatever approach ends up making it into `master` should not be specific to pytest (even though it is also my personally preferred testing tool) but should work with as many scenarios/requirements as possible.

I see these approaches right now, and none of them seem to capture all of the goals:
1. Generate code (basically off the table: too many steps, clunky, fragile)
2. Dynamically add test methods within suites owned by `climactic`
3. Dynamically add test methods to a class/module that is defined by the user (user provides a hook)
4. Option 4 ;) something that I don't know about integrating with existing testing frameworks yet. I guess this requires looking into the various test collectors and seeing what is already exposed.

**Comment by RonnyPfannschmidt** [comment]
step one would be factoring out execution and parsing,
then both unittest based execution and a pytest plugin should be trivial

**Comment by b33j0r** [comment]
I actually was not aware of this: https://pytest.org/latest/plugins.html#setuptools-entry-points

Cool!

Edit: even better: https://pytest.org/latest/example/nonpython.html#yaml-plugin

**Comment by b33j0r** [comment]
I just created a PR (https://github.com/b33j0r/climactic/pull/6) that registers a climactic pytest plugin, and it actually does work. Definitely not a complete solution yet.

**Comment by b33j0r** [comment]
Just merged into master. I also incorporated Ronny's suggestion on the PR about allowing the file pattern to be configurable in Pytest's .ini system.

**Comment by b33j0r** [comment]
I'm not sure about the priority of supporting features like fixtures at this time, but you are welcome to open a new issue and/or submit a PR! Thanks for the suggestions
