### ISSUE TITLE
not using yaml tags to model the actions

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [b33j0r/climactic#3]
yaml allows you to register tags to parse into datatypes

in my opinion it would be a more nice method to express the actions, which are currently single element mappings

example:

```
#!yaml

---
# A very simple test!

- !run >
    echo Hello world!
- !assert-output >
    Hello world!
```

**Comment by b33j0r** [comment]
This does make sense. Keep in mind that the goal of using YAML in the first place is to keep the test writing as simple as possible. A concern was that this would reduce readability; however, your example above is actually more readable, at least to my eyes (an exclamation mark in the context almost suggests that "some action will be performed"). I will consider this... Aside from using more of the YAML spec, could you please list any advantages?

**Comment by RonnyPfannschmidt** [comment]
using tags its possible to make things directly into a domain object for expressing actions and similar details

**Comment by b33j0r** [comment]
Initial implementation is in PR https://github.com/b33j0r/climactic/pull/8

Would appreciate a code review, noting that the goal is to incrementally improve this package. The solution is essentially to keep the existing design, but to register each command with pyyaml as the first constructor option

edit: there are some specific things I would like to add (soon):
- parse a top-level "!test" tag that can provide metadata in addition to actions (but which can also be omitted)
- tighten up the error handling

things I don't want to add at this time:
- arbitrary object parsing (!!python stuff doesn't fit yet)

**Comment by RonnyPfannschmidt** [comment]
at first glance it looks like it would be nicely possible to extract more details now, i#m not sure when i can do more review

**Comment by b33j0r** [comment]
I'm happy with it as an incremental improvement. I still want to revisit a refactor of parsing versus representation and execution. As I get into the PyYaml API, it's a little bit harder to extend than I would have hoped.

For example, I can't immediately identify how to create a constructor hook for a root node. I'm used to BNF, Yacc/Lex, LALR; those kinds of constructs. This tag model doesn't immediately lend itself to that kind of thinking, so I'll have to think harder. But I'm going to go ahead and merge this change for now.
